version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbArquiTpG25
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"